version: "3.8"

volumes:
  minecraft_data:

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - ${CONFIG_DIR:-/mnt/c/podmandemo}/minecraft/data:/data
    restart: unless-stopped
