version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:2.7
    ports:
      # proxy entrypoints
      - 80:80/tcp # web
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/traefik/providers:/config
      - ${CONFIG_DIR}/traefik/certs:/etc/certs
    command:
      - "--entrypoints.web.address=:80/tcp"
      - "--providers.docker"
      - "--providers.docker.defaultRule=Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
      - "--api.insecure=true"
      - "--log=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
    labels:
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_URL}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=web
    restart: unless-stopped

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
