version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ${CONFIG_DIR:-/mnt/c/podmandemo}/mosquitto/data:/mosquitto/data
      - ${CONFIG_DIR:-/mnt/c/podmandemo}/mosquitto/log:/mosquitto/log
      - ${CONFIG_DIR:-/mnt/c/podmandemo}/mosquitto/config:/mosquitto/config
    restart: unless-stopped
